Procfile
backend/Procfile

Created Procfile for Heroku deployment.
N/A

Created Procfile for Heroku deployment

---

front-end/.gitignore
front-end/src/components/ResetPassword/ResetPassword.js
front-end/src/components/jobContainer/jobsContainer.js

Corrects file paths, changes ResetPassword component name, removes duplicate line from .gitignore

Fixes after merge

---

backend/config/middleware.js
backend/routers/router.js

Updated middleware.js with router.js, in routes.js created post, put, delete jobs
Routes will be tested using Postman once DB has been established 
- [   ] My code has been reviewed by at least one peer
- [  ] I have added tests that prove my fix is effective or that my feature works
- [  ] New and existing unit tests pass locally with my changes
- [  ] There are no merge conflicts

*Pending DB to Merge* Created Backend Endpoints (Post, Put, Delete) -Jobs 

---

front-end/src/components/SingleJob/singleJob.js
front-end/src/components/jobContainer/jobsContainer.js
front-end/src/components/jobList/job.js
front-end/src/components/jobList/jobList.js
front-end/src/components/search/search.js

search function working
fixed search function

Displaying data

---

backend/db/config.js
backend/knexfile.js
backend/package.json

updated knexfile in attempt to try and run migrations
n/a
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] Incomplete/work-in-progress, PR is for discussion/feedback
n/a
- [x ] My code follows the style guidelines of this project
- x[ ] I have performed a self-review of my own code
- [x ] My code has been reviewed by at least one peer
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [ x] I have added tests that prove my fix is effective or that my feature works
- [x ] New and existing unit tests pass locally with my changes
- [ x] There are no merge conflicts

Postgres deployment

---

backend/Procfile
backend/package.json

updated procfile 
1
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] Complete, but not tested (may need new tests)
n/a
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [x ] My code has been reviewed by at least one peer
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [x ] I have added tests that prove my fix is effective or that my feature works
- [x ] New and existing unit tests pass locally with my changes
- [x ] There are no merge conflicts

updated procfile

---

front-end/src/App.js
front-end/src/components/Routes/Routes.js
front-end/src/constants/routes.js
front-end/yarn.lock

Reorganizes React files

---

front-end/src/components/jobContainer/jobsContainer.js

Fix attempt for react routes

---

backend/routers/router.js
front-end/src/components/postJob/employerNavigation.js
front-end/src/components/postJob/jobForm.js
front-end/src/components/postJob/jobFormStyling.js
front-end/src/components/postJob/postJob.js

Added both of the get endpoints.
Waiting for database to be added

Get endpoints

---

backend/db/migrations/20190110134322_jobs.js

migration table

---

backend/routers/router.js

added routes for users, still need to be tested
n/a
- [x ] New feature (non-breaking change which adds functionality)
- [x ] Complete, but not tested (may need new tests)
n/a
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [x ] My code has been reviewed by at least one peer
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [x ] I have added tests that prove my fix is effective or that my feature works
- [ x] New and existing unit tests pass locally with my changes
- [ x] There are no merge conflicts

added routes for users, still need to be tested

---

front-end/netlify.toml

Adds settings for netlify.toml file

Adds settings for netlify.toml file

---

front-end/netlify.toml
netlify.toml

Changes to netlify.toml file

---

backend/routers/router.js

Added All Server Side User endpoints
n/a
- [ x] New feature (non-breaking change which adds functionality)
- [x ] Complete, but not tested (may need new tests)
-testing locally is not working on my computer
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ x] My code has been reviewed by at least one peer
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [ x] I have added tests that prove my fix is effective or that my feature works
- [x ] New and existing unit tests pass locally with my changes
- [x ] There are no merge conflicts

Added All Server Side User endpoints

---

backend/db/seeds/002-jobs.js

Please include a summary of the change and a link to which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
fixed seed error

fixed seeds

---

backend/config/middleware.js
backend/package-lock.json
backend/package.json
backend/routers/stripeRouter.js
backend/stripeServer.js

Created a stripe server for POST routes to create a payment
Test was not conducted because frontend billing form will have to be configured to the backend billing Stripe server. It would pass if data matched

Stripe server

---

backend/knexfile.js

updated knex file with PG object

added object to knex file

---

backend/knexfile.js

updated knex file
n/a
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] Complete, but not tested (may need new tests)
n/a

updated knexfile.js

---

backend/db/seeds/02-jobs.js
backend/routers/router.js

Changed server to router in router folder
1

changed word server to router

---

front-end/package.json
front-end/src/components/billing/billing.js
front-end/src/components/billing/checkoutForm.js
front-end/yarn.lock

Created stripe billing form
Validation states that card info is not a secured line but it works

Created Stripe Billing Form

---

backend/routers/router.js

updated endpoint

---

front-end/src/components/billing/billing.js
front-end/src/components/billing/billingCheckout.js
front-end/src/components/billing/checkoutForm.js

Fixed Stripe Error - Test Post Works and token received when card data is entered and stored on my Stripe Dashboard under test data: Please see Request POST Body and Response Body attachments below.
Tested and stored in Stripe Dashboard with screenshots attached

Fixed Stripe Error - Test Post Works and token received when card data is entered

---

backend/db/seeds/03-jobs.js

Renames keys within jobs seeds

Renames keys within jobs seeds

---

backend/db/seeds/02-users.js

Defines id in users seeds

---

front-end/src/components/billing/checkoutForm.js

Fix radio button to show in console which payment method was selected. Fixed proptype regarding radio button selections working. Stripe has full functionality and can be viewed in console as well as on the dashboard. [See Stipe Trello Card](https://trello.com/c/H473rdZF/45-billing-page)
Fixed radio button functionality and proptype error in console
Stripe dashboard and console

Fix proptype radiobutton refreshdata

---

front-end/package.json
front-end/src/components/CompanyProfile/profilePic.js
front-end/yarn.lock

added a page to insert a profile pic

Cloudinary

---

backend/routers/router.js

fix endpoint to return single job

updated route for one job

---

front-end/src/App.css
front-end/src/App.js
front-end/src/components/NavBar/employerLogin.js
front-end/src/components/NavBar/navBar.css
front-end/src/components/Toolbar/Toolbar.css
front-end/src/components/Toolbar/Toolbar.js

just provides links to routes
local host

routes on top of page

---

front-end/src/App.js

deleted wrong line of code when fixing merge conflicts
fixed app.js
- [] Complete, but not tested (may need new tests)
locally on host

fixes App.js issue

---

front-end/src/components/billing/billing.js
front-end/src/components/billing/billingCheckout.js
front-end/src/components/billing/checkoutForm.js

Refactored the Stripe Billing to have Buttons displayed for a pop-up modal for each service provided. Routes will need to be refactored on the backend which I am currently working on but everything works on the frontend
Console testing, breaking on the backend because the routes are not aligned but once it is merged then I can connect the two and it will be working on localhost:8000

Refactoring billing

---

front-end/src/components/Landing/jobsContainer.js
front-end/src/components/Routes/Routes.js

hopefully fixes issue this time
file naming
local host

another attempt to fix naming

---

front-end/src/components/CompanyProfile/updateProfile.js

connected profilePic to updateform

added profilePic to updateProfile

---

front-end/src/components/Landing/jobList.js
front-end/src/components/Landing/jobsContainer.js
front-end/src/components/Routes/Routes.js
front-end/src/components/postJob/jobForm.js
front-end/src/components/postJob/postJob.js

changed naming of file imports to get rid of errors
app is displaying locally

changed naming of file imports to get rid of errors

---

front-end/src/components/CompanyProfile/updateProfile.js
front-end/src/components/Landing/jobsContainer.js

fixed small errors on naming conventions
Error removed upon uncommenting and change in lowercase from uppercase

fixed small errors on naming conventions

---

front-end/src/components/Landing/job.js
front-end/src/components/Landing/jobsContainer.js

removed commented information to render data. 

removing test data

---

backend/db/migrations/20190110134322_jobs.js

changed timestamp to only show date

changed timestamp to only show date

---

front-end/src/App.js
front-end/src/components/Navigation/NavigationStyles.css
front-end/src/components/Navigation/SideMenu.js
front-end/src/components/SignOut/SignOut.css
front-end/src/components/SignOut/SignOut.js

Adds the Sign Out option to the side nav menu.
Sets side nav menu view for users who logged in and those who aren't

Adds Sign Out to nav menu, options conditional on log in status

---

front-end/src/components/CompanyProfile/profilePic.js

Removed button once a profile picture is uploaded. 

add image button is removed when image uploaded

---

backend/routers/__tests__/router.js

add test routes
none
couldn't do much with the database not connecting for me

Route endpoints tests

---

front-end/src/components/billing/billing.js
front-end/src/components/billing/billingCheckout.js
front-end/src/components/billing/checkoutForm.js

Refactored stripe form to mimic the docs standard react stripe form ( will be adjusted )
I have manually tested locally on my machine but it is only tested on the frontend part with functionality and being refreshed once Buy Now button has been pressed

Stripe Form Refactor

---

backend/stripe/index.js
backend/stripe/package.json
backend/stripe/payment.js
backend/stripe/server.js
front-end/src/components/billing/billing.js
front-end/src/components/billing/billingCheckout.js
front-end/src/components/billing/checkoutForm.js

Got the frontend and backend communicating together to retrieve token and successful payment
I have manually tested this form via console and stripe dashboard. I have a successful modal to appear demonstrating that payment was received.

Stripe server refactor

---

backend/stripe/server.js
front-end/package.json
front-end/src/components/billing/billing.js
front-end/yarn.lock

Completed a rollback of the Stripe API keys to be used as variables in our app 
Once merged will be tested against our data, locally it works

Rollback keys refactor

---

backend/knexfile.js
front-end/src/components/CompanyProfile/newProfileForm.js
front-end/src/components/billing/billing.js

working on functionality of new user form and changed syntax on billing form 
1
tested locally

working on functionality of new user form and changed syntax in billing

---

front-end/src/components/Landing/landingStyling.css
front-end/src/components/Landing/singleJob.js

adding styling to individual job page for both desktop and mobile

Styling tablet mobile

---

front-end/src/components/CompanyProfile/newProfileForm.js
front-end/src/components/CompanyProfile/newProfileFormStyling.css
front-end/src/components/CompanyProfile/profilePic.js

styling for the new user form page
n/a
locally

New user form

---

front-end/src/components/CompanyProfile/newProfileForm.js
front-end/src/components/CompanyProfile/newProfileFormStyling.css
front-end/src/components/CompanyProfile/profileForm.js
front-end/src/components/CompanyProfile/profileFormStyling.css
front-end/src/components/CompanyProfile/profilePic.js
front-end/src/components/CompanyProfile/updateProfile.js

Completed desktop view styling for updating profile page
n/a
locally

Update profile form

---

backend/__tests__/authRouter.js
backend/routers/authRouter.js
front-end/src/App.js
front-end/src/components/Firebase/firebase.js
front-end/src/components/RedirectPage/RedirectPage.js
front-end/src/components/Routes/Routes.js
front-end/src/components/SignIn/SignIn.js
front-end/src/components/SignUp/SignUp.js

End points to check if user_uid exists in 'login' and 'users' table
Redirecting logic for user sign up with email/password
Redirect logic for user sign in with Google OAuth (only complete in SignUp component)
Comments out Redirect component until further notice

User creation endpoints, redirecting for sign up and sign in

---

front-end/src/components/CompanyProfile/newProfileForm.js
front-end/src/components/Routes/Routes.js

working on posting a new user
n/a
still testing

working on post functionality for adding a new user

---

front-end/src/components/postJob/jobForm.js
front-end/src/components/postJob/postJob.js

added main functionalities to post job page
none
checking state

Post job functionality

---

front-end/src/components/CompanyProfile/updateProfile.js
front-end/src/components/Landing/landingStyling.css
front-end/src/components/Routes/Routes.js

updated route and added id to updateform

Fixing errors

---

backend/db/migrations/20190109113115_users_table.js
front-end/src/components/CompanyProfile/newProfileForm.js
front-end/src/components/CompanyProfile/updateProfile.js

fixed migration to be defaulted to 0, and changed names in the new user form and update profile form
2

Updated migration, and changed user being passed in to match requirement

---

backend/db/migrations/20190110134322_jobs.js
backend/db/migrations/20190123131736_jobs_category.js
backend/db/seeds/03-jobs.js
backend/routers/router.js
front-end/src/components/Landing/categories.js
front-end/src/components/Landing/jobsContainer.js
front-end/src/components/Landing/landingStyling.css
front-end/src/components/Navigation/SideMenu.js
front-end/src/components/SignIn/SignIn.js
front-end/src/components/SignUp/SignUp.js

Completes search by category functionality
Fixes typos

Search categories, typo fixes

---

front-end/src/components/Landing/jobList.js

Please include a summary of the change and a link to which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
This is not your typical PR. I need to add a single console log because Netlify is not correctly passing props down to one of our components and I need to debug it.

Add console log to debug Netlify props issue

---

backend/stripe/server.js
front-end/src/components/billing/billing.js
front-end/src/components/billing/checkoutForm.js

Reversed everything back to its original state in Stripe to work backwards only to discover that the publishable test key was expired that was posted in our recent code #92. 
Fixes #92 
Console and viewing the routes in the network tab displaying the status codes along with the successful messages on a charge and token request

Reversed everything --- Expired Key Fixed (#92)

---

front-end/src/components/Landing/jobsContainer.js
front-end/src/components/SignUp/SignUp.js

Adds user creation for Sign Up with email/password
Fixes typo

bug fix and typo

---

backend/routers/router.js
front-end/src/components/CompanyProfile/profileForm.js
front-end/src/components/CompanyProfile/updateProfile.js

company info is displayed and can be edited

Company pages

---

backend/stripe/server.js
front-end/src/components/billing/checkoutForm.js

Added radio buttons along with the server logic to mirror the data the form is submitting. The radio buttons currently are not fully functional but payment is still working otherwise
Data has been tested in the browser with a payment successful located in browser and in console. Just no radio functionality - yet

Added Radio Buttons - Need assistance in fixing radio buttons functionality -- payment works still

---

front-end/src/components/billing/checkoutForm.js

changed the value to match what was being set in state so the radio buttons would fill in when selected
1
locally

fixed radio buttons

---

backend/routers/jobsRouter.js
backend/routers/router.js
front-end/src/components/CompanyProfile/newProfileForm.js
front-end/src/components/Landing/header.js
front-end/src/components/Landing/jobsContainer.js
front-end/src/components/Routes/Routes.js
front-end/src/components/SignIn/SignIn.js
front-end/src/components/billing/UserJobs.js
front-end/src/components/billing/billing.js
front-end/src/components/postJob/EditJob.js
front-end/src/components/postJob/jobForm.js
front-end/src/components/postJob/postJob.js
front-end/src/constants/routes.js

Post and edit jobs features
Billing page lists all of a users jobs

Post/Edit jobs, user jobs listed on billing page

---

backend/routers/jobsRouter.js
front-end/src/components/Landing/jobsContainer.js
front-end/src/components/postJob/EditJob.js
front-end/src/components/postJob/jobForm.js
front-end/src/components/postJob/postJob.js

Adds category field to post and edit job

Adds category field to post and edit job

---

front-end/src/components/CompanyProfile/profileForm.js
front-end/src/components/billing/billing.js
front-end/src/components/billing/checkoutForm.js
front-end/src/components/billing/checkoutForm.scss

design for billing page: desktop and mobile
n/a
locally

Responsive design

---

front-end/src/components/CompanyProfile/profileForm.js
front-end/src/components/CompanyProfile/profilePic.js
front-end/src/components/CompanyProfile/updateProfile.js

can now add an image to company profile

can now add a profile pic

---

front-end/src/components/billing/checkoutForm.scss

fixed an error with the billing page in mobile view
1
locally

updated mobile view styling on billing page

---

front-end/src/components/CompanyProfile/updateProfile.js
front-end/src/components/Landing/singleJob.js
front-end/src/components/Landing/singleJobStyling.scss

fix sytling issue

---

backend/knexfile.js
backend/yarn.lock
front-end/src/components/billing/checkoutForm.js
front-end/src/components/billing/checkoutForm.scss

Moved the Purchase Successful modal to the center of the screen
Tested in browser

Billing style purchase complete

---

netlify.toml

update toml file
1
in progress

updated toml file again

---

netlify.toml

Description
update toml file
1
Type of change
Bug fix (non-breaking change which fixes an issue)
Change status
Complete, tested, ready to review and merge
Complete, but not tested (may need new tests)
Incomplete/work-in-progress, PR is for discussion/feedback
How Has This Been Tested?
in progress
Checklist:
My code follows the style guidelines of this project
I have performed a self-review of my own code
My code has been reviewed by at least one peer
I have commented my code, particularly in hard-to-understand areas
I have made corresponding changes to the documentation
My changes generate no new warnings
I have added tests that prove my fix is effective or that my feature works
New and existing unit tests pass locally with my changes
There are no merge conflicts

updated toml file back to pointing to front-end/build

---

front-end/src/components/CompanyProfile/newProfileForm.js
front-end/src/components/CompanyProfile/updateProfile.js
front-end/src/components/CompanyProfile/updateProfileStyling.scss
front-end/src/components/Landing/singleJobStyling.scss

Please include a summary of the change and a link to which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

passed update to profile form

---

front-end/src/components/Landing/categories.js
front-end/src/components/Landing/landingStyling.scss

added category bar styling for mobile view
1
locally

added category bar styling for mobile

---

front-end/src/components/CompanyProfile/profileForm.js
front-end/src/components/CompanyProfile/profileInfo.js
front-end/src/components/CompanyProfile/updateProfile.js
front-end/src/components/CompanyProfile/updateProfileStyling.scss

added loading bars to update page and updated styling

Fixing display

---

front-end/src/components/Navigation/SideMenu.js

removed single job tab from menu
locally

removed single job tab from menu

---

front-end/src/components/billing/UserJobs.js
front-end/src/components/billing/checkoutForm.scss

styled job listings

---

front-end/src/components/Landing/landingStyling.scss
front-end/src/components/Navigation/navigationStyling.scss
front-end/src/components/billing/checkoutForm.js
front-end/src/components/billing/checkoutForm.scss

Billing page layout in desktop format. A few details not implemented that needs to be addressed and worked on
This is currently a work in progress. Need to speak with the team to address styling issues I am having

Billing-Desktop --WIP

---

front-end/src/components/postJob/jobForm.js
front-end/src/components/postJob/postJob.js
front-end/src/components/postJob/postJobStyling.scss
front-end/src/default.scss

post job desktop complete
localhost

Post job v2

---

front-end/src/components/billing/Balance.js
front-end/src/components/billing/UserJobs.js
front-end/src/components/billing/billing.js
front-end/src/components/billing/checkoutForm.js
front-end/src/components/billing/checkoutForm.scss
front-end/src/components/billing/temp-file.js

Divided up sections to be left and right sides. Nested elements a bit messy but works. Fluidity needs help. 
n/a

Billing desktop ui - Part II --WIP

---

front-end/src/components/Routes/Routes.scss
front-end/src/components/billing/Balance.js
front-end/src/components/billing/UserJobs.js
front-end/src/components/billing/billing.js
front-end/src/components/billing/checkoutForm.js
front-end/src/components/billing/checkoutForm.scss
front-end/src/components/billing/temp-file.js
front-end/src/default.scss

fixed structure of billing
local host

Billing fix attempt

---

front-end/src/App.js
front-end/src/components/Landing/header.js
front-end/src/components/Landing/jobsContainer.js
front-end/src/components/Landing/landingStyling.scss
front-end/src/components/Landing/search.js
front-end/src/components/Navigation/Footer.js
front-end/src/components/Navigation/Navbar.js
front-end/src/components/Navigation/SideMenu.js
front-end/src/components/Navigation/navigationStyling.scss
front-end/src/components/Routes/Routes.js
front-end/src/components/Routes/Routes.scss
front-end/src/variables-mixins.scss

Desktop View:
The navbar is styled, but has a minor bug. The hamburger side menu is complete, and the header and search function are complete
locally

Nav Bar & Landing Page header & search

---

front-end/public/index.html
front-end/src/components/CompanyProfile/profileForm.js
front-end/src/components/CompanyProfile/profileFormStyling.scss
front-end/src/components/CompanyProfile/profileInfo.js
front-end/src/components/CompanyProfile/updateProfile.js
front-end/src/components/Landing/singleJob.js
front-end/src/components/Landing/singleJobStyling.scss

styling for single job page and profile forms

Edit page styling

---

front-end/src/components/billing/UserJobs.js
front-end/src/components/billing/checkoutForm.js
front-end/src/components/billing/checkoutForm.scss

Completed for the most part the desktop design. There are a few minor cosmetics that needs to be complete and need team feedback on how to approach these changes
n/a

Billing desktop ui - Part 3 --Minor Adjustments needed

---

front-end/src/components/postJob/jobForm.js
front-end/src/components/postJob/postJobStyling.scss

Post job mobile tablet

---

front-end/public/index.html
front-end/src/components/billing/Balance.js
front-end/src/components/billing/PaymentModal.js
front-end/src/components/billing/UserJobs.js
front-end/src/components/billing/billing.js
front-end/src/components/billing/checkoutForm.js
front-end/src/components/billing/checkoutForm.scss
front-end/src/components/postJob/postJobStyling.scss
front-end/src/index.scss
front-end/src/variables-mixins.scss

mobile and tablet styling complete
localhost

Billing page

---

front-end/src/components/CompanyProfile/profileFormStyling.scss
front-end/src/components/CompanyProfile/profileInfo.js
front-end/src/components/CompanyProfile/updateProfile.js
front-end/src/components/Landing/singleJob.js
front-end/src/components/Landing/singleJobStyling.scss

Design job profile

---

front-end/src/components/Landing/singleJob.js
front-end/src/components/Landing/singleJobStyling.scss

new loader

---

front-end/src/components/CompanyProfile/profilePic.js

added variables for picture profile

---

CODE_OF_CONDUCT.md

Added Code of Conduct to our project
Data via md no test necessary

Adding Code of Conduct md document

---

front-end/src/components/billing/checkoutForm.js

got cancel button to clear out form once clicked
Tested locally in browser

Cancel button clears form

---

front-end/src/components/billing/checkoutForm.js

payment refreshes already when payment is successful - updated comment
Tested in browser

payment refreshes already when payment is successful - updated comment

---

backend/knexfile.js
front-end/src/components/CompanyProfile/ChangePasswordModal.js
front-end/src/components/CompanyProfile/ChangePasswordModal.scss
front-end/src/components/CompanyProfile/profileForm.js
front-end/src/components/CompanyProfile/profileFormStyling.scss
front-end/src/components/CompanyProfile/profileInfo.js
front-end/src/components/CompanyProfile/updateProfile.js
front-end/src/components/Firebase/firebase.js
front-end/src/index.scss

Change password modal with complete functionality

Change password

---

front-end/src/components/billing/checkoutForm.js

Got auto job credits to work and update when payment has been successful
Tested payment locally and stripe dashboard displays payment

Auto update jobs

---

front-end/src/components/billing/checkoutForm.js
front-end/src/components/billing/checkoutForm.scss

Styled the error message that pops up when none of the radio buttons are selected and when you are trying to purchase a payment
Tested in the browser in the console before rendering code in vscode

Styled option message

---

front-end/src/components/CompanyProfile/newProfileForm.js
front-end/src/components/CompanyProfile/profileForm.js
front-end/src/components/CompanyProfile/profileInfo.js
front-end/src/components/CompanyProfile/updateProfile.js
front-end/src/components/Landing/jobsContainer.js

account profile page allows for the user the ability to sign up and see their info updated after they do. I also added an alt tag.

Profile bugs

---

front-end/src/components/CompanyProfile/newProfileFormStyling.scss

Changed placeholder text to be roboto instead of default
1
locally

changed company summary placeholder text 

---

front-end/src/components/billing/checkoutForm.js

fixed cancel button which was going to a blank screen, now just clears the billing form. 

fixed cancel button

---

front-end/src/components/CompanyProfile/profileForm.js
front-end/src/components/CompanyProfile/profileFormStyling.scss
front-end/src/components/Landing/landingStyling.scss
front-end/src/components/postJob/jobForm.js
front-end/src/components/postJob/postJobStyling.scss

Bug fixes v2

---

front-end/src/components/CompanyProfile/profileFormStyling.scss

color change of text
- [] Complete, tested, ready to review and merge
has not been

edit page color changes

---

front-end/src/auth-styles.scss
front-end/src/components/CompanyProfile/newProfileForm.js
front-end/src/components/CompanyProfile/profileFormStyling.scss
front-end/src/components/CompanyProfile/updateProfile.js
front-end/src/components/Landing/singleJobStyling.scss
front-end/src/components/billing/Balance.js
front-end/src/components/billing/UserJobs.js
front-end/src/components/billing/checkoutForm.js
front-end/src/components/billing/checkoutForm.scss
front-end/src/components/postJob/EditJob.js
front-end/src/components/postJob/jobForm.js

Resolves console errors and warnings
Updates default avatar to rehosted URL
Fixes active/college degree toggle on update
Minor styling changes to standardize across project

Fixes small inconsistencies, resolves console errors, updates rehosted default avatar
